services:
  - type: web
    name: preview-engine
    env: node
    buildCommand: npm install && NODE_ENV=development npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
